name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Check cache
        uses: actions/cache@v2
        id: cache
        with:
          path: |
            node_modules
            # Add any other directories or files that you want to cache here
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
      
      - name: Build HTML/CSS
        run: |
          # Add any commands here that you need to run to build your HTML/CSS files.
          # For example:
          # npm run build

      - name: Save cache
        uses: actions/cache@v2
        with:
          path: |
            node_modules
            # Add any other directories or files that you want to cache here
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: ${{ runner.os }}-node-