name: Greetings

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      continue-on-error: true
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: 'Thank you and congratulations 🎉 for opening your very first issue in keploy. Please adhere to our [Code Of Conduct](https://github.com/keploy/keploy/blob/main/CODE_OF_CONDUCT.md).
          Incase you want to claim this issue, please comment down below! We will try to get back to you as soon as we can.👀
          Feel free to join us on [Keploy Slack](https://join.slack.com/t/keploy/shared_invite/zt-12rfbvc01-o54cOG0X1G6eVJTuI_orSA) by dropping an email [here](mailto:support@keploy.io).👩‍💻 We would love to hear your interesting ideas and engage in discussions.'
        pr-message: 'Thank you and congratulations 🎉 for opening your very first pull request in keploy.
        We will review it soon! Till then you can checkout the `README.md` for more details on it.'